export { default as Home } from './Home/Home'
export { default as ErrorPage } from './Error/Error-page'
export { default as User } from './User/User'
export { default as Login } from './Login/Login'
export { default as CreateAccount } from './CreateAccount/CreateAccount'
export { default as Pruebas } from './Pruebas/Pruebas'
